// A webes nézet szövegei (magyar, angol). A {brand} helyére a márkanév
// kerül (../brand.js).

export const TEXTS = {
  hu: {
    title: 'Webes nézet',
    loginTitle: 'Naplóm a weben',
    loginLead: 'Lépj be az online fiókoddal. A jelszavadból a böngésző számolja ki a kulcsot, és a titkosított mentésed itt, a gépeden nyílik ki.',
    email: 'E-mail-cím',
    password: 'Jelszó',
    login: 'Belépés',
    loginNote: 'A jelszó nem hagyja el a gépet, és semmi nem marad a böngészőben: a fül bezárásakor vagy újratöltéskor újra be kell lépni.',
    back: '← Vissza a főoldalra',
    stepKeys: 'Kulcsok készítése…',
    stepLogin: 'Belépés…',
    stepDownload: 'A mentés letöltése…',
    stepOpen: 'Kibontás…',
    errCredentials: 'Hibás e-mail-cím vagy jelszó.',
    errNotConfirmed: 'Az e-mail-címed még nincs megerősítve: nézd meg a leveleidet.',
    errNetwork: 'Nincs kapcsolat a szerverrel. Próbáld újra.',
    errNoBackup: 'Még nincs online mentés. Az appban: Profil → Online fiók → Mentés most.',
    errOpen: 'A mentést nem sikerült kibontani (más jelszóval készült?).',
    errUnknown: 'Valami hiba történt. Próbáld újra.',
    navLog: 'Napló',
    navStats: 'Statisztika',
    navDiet: 'Étrend',
    navMedals: 'Érmek és barátok',
    navMedalsShort: 'Érmek',
    backupAt: 'Mentés: {when}',
    logout: 'Kilépés',
    refresh: 'Frissítés: a legújabb mentés betöltése',
    refreshDone: 'Frissítve: a legújabb mentés betöltve.',
    refreshNone: 'Nincs újabb mentés. Az appban: Mentés most, és utána frissíts újra.',
    errExpired: 'A belépés lejárt. Lépj be újra.',
    themeLight: 'Világos téma',
    themeDark: 'Sötét téma',
    styleNotebook: 'Füzet stílus',
    stylePlain: 'Megszokott stílus',
    otherLang: 'English',
    readOnly: 'Csak megtekintés: szerkeszteni a telefonon lehet.',
    logEmpty: 'Még nincs edzés vagy kardió a mentésben.',
    more: 'Régebbiek',
    minutes: '{n} perc',
    sets: '{n} sorozat',
    volume: '{kg} kg megmozgatva',
    deload: 'deload',
    pace: '{pace} /km',
    kcalApprox: 'kb. {n} kcal',
    statThisWeek: 'Edzés a héten',
    statTotal: 'Összes edzés',
    statVolume30: 'Megmozgatott súly (30 nap)',
    statCardio30: 'Kardió-táv (30 nap)',
    statWeight: 'Testsúly',
    chartWorkouts: 'Edzések hetente',
    chartVolume: 'Megmozgatott súly hetente (kg)',
    chartWeight: 'Testsúly (kg)',
    chartLift: 'Becsült 1RM',
    liftBest: 'Csúcs: {value} ({set}, {date})',
    noData: 'Ehhez még kevés az adat.',
    dietEmpty: 'Még nincs étkezésnapló a mentésben.',
    dietKcal: 'Kalória',
    dietProtein: 'Fehérje',
    dietPlanned: 'tervezett: +{n} kcal',
    dietMeals: '{n}/3 fő étkezés',
    planned: 'terv',
    servings: '{n} adag',
    slot_breakfast: 'Reggeli',
    slot_morningSnack: 'Tízórai',
    slot_lunch: 'Ebéd',
    slot_afternoonSnack: 'Uzsonna',
    slot_dinner: 'Vacsora',
    slot_snack: 'Nasi',
    medalsTitle: 'Érmek',
    medalsCount: '{got}/{total} szint',
    friendsTitle: 'Barátok a héten',
    friendsRankHint: 'Az e heti edzések (hétfőtől); a részletes napló soha nem látszik.',
    friendsNone: 'Még nincs barátod. Az appban a Barátok oldalon jelölheted őket.',
    friendsOffline: 'A barátok most nem tölthetők be.',
    you: 'Te',
    workoutsOfGoal: '{n}/{goal} edzés',
    cardioCount: '{n} kardió',
    tier1: 'Bronz',
    tier2: 'Ezüst',
    tier3: 'Arany',
    tier4: 'Gyémánt',
    tier0: 'még nincs',
    ach_workouts: 'Edzések',
    ach_weeklyStreak: 'Heti sorozat',
    ach_volume: 'Megmozgatott súly',
    ach_records: 'Rekordok',
    ach_bench: 'Fekvenyomás',
    ach_squat: 'Guggolás',
    ach_deadlift: 'Felhúzás',
    ach_overheadPress: 'Katonai nyomás',
    ach_runs: 'Kardió',
    ach_mealDays: 'Étrend',
    ach_weighIns: 'Mérések',
    ach_challenges: 'Napi kihívások',
    ach_challengeStreak: 'Kihívás-sorozat',
    ach_teamChallenges: 'Csapatjátékos',
    act_run: 'Futás',
    act_walk: 'Gyaloglás',
    act_cycling: 'Kerékpár',
    act_rowing: 'Evezés',
    act_swimming: 'Úszás',
    act_elliptical: 'Elliptikus tréner',
    act_jumpRope: 'Ugrókötél',
    act_stairs: 'Lépcsőzés',
    act_hiit: 'HIIT',
    act_custom: 'Saját tevékenység',
  },
  en: {
    title: 'Web view',
    loginTitle: 'My log on the web',
    loginLead: 'Log in with your online account. Your browser derives the key from your password, and your encrypted backup opens right here on your computer.',
    email: 'Email',
    password: 'Password',
    login: 'Log in',
    loginNote: 'Your password never leaves your computer and nothing stays in the browser: after closing or reloading the tab you log in again.',
    back: '← Back to the home page',
    stepKeys: 'Preparing keys…',
    stepLogin: 'Logging in…',
    stepDownload: 'Downloading the backup…',
    stepOpen: 'Opening…',
    errCredentials: 'Wrong email or password.',
    errNotConfirmed: 'Your email address is not confirmed yet: check your inbox.',
    errNetwork: 'Cannot reach the server. Please try again.',
    errNoBackup: 'No online backup yet. In the app: Profile → Online account → Back up now.',
    errOpen: 'The backup could not be opened (made with a different password?).',
    errUnknown: 'Something went wrong. Please try again.',
    navLog: 'Log',
    navStats: 'Statistics',
    navDiet: 'Diet',
    navMedals: 'Medals & friends',
    navMedalsShort: 'Medals',
    backupAt: 'Backup: {when}',
    logout: 'Log out',
    refresh: 'Refresh: load the latest backup',
    refreshDone: 'Updated: the latest backup is loaded.',
    refreshNone: 'No newer backup. In the app: Back up now, then refresh again.',
    errExpired: 'Your session expired. Please log in again.',
    themeLight: 'Light theme',
    themeDark: 'Dark theme',
    styleNotebook: 'Notebook style',
    stylePlain: 'Regular style',
    otherLang: 'Magyar',
    readOnly: 'View only: edit on your phone.',
    logEmpty: 'No workouts or cardio in the backup yet.',
    more: 'Older',
    minutes: '{n} min',
    sets: '{n} sets',
    volume: '{kg} kg lifted',
    deload: 'deload',
    pace: '{pace} /km',
    kcalApprox: 'approx. {n} kcal',
    statThisWeek: 'Workouts this week',
    statTotal: 'Total workouts',
    statVolume30: 'Volume (30 days)',
    statCardio30: 'Cardio distance (30 days)',
    statWeight: 'Body weight',
    chartWorkouts: 'Workouts per week',
    chartVolume: 'Volume per week (kg)',
    chartWeight: 'Body weight (kg)',
    chartLift: 'Estimated 1RM',
    liftBest: 'Best: {value} ({set}, {date})',
    noData: 'Not enough data yet.',
    dietEmpty: 'No meal log in the backup yet.',
    dietKcal: 'Calories',
    dietProtein: 'Protein',
    dietPlanned: 'planned: +{n} kcal',
    dietMeals: '{n}/3 main meals',
    planned: 'planned',
    servings: '{n} servings',
    slot_breakfast: 'Breakfast',
    slot_morningSnack: 'Morning snack',
    slot_lunch: 'Lunch',
    slot_afternoonSnack: 'Afternoon snack',
    slot_dinner: 'Dinner',
    slot_snack: 'Snack',
    medalsTitle: 'Medals',
    medalsCount: '{got}/{total} tiers',
    friendsTitle: 'Friends this week',
    friendsRankHint: 'Workouts this week (from Monday); your detailed log is never shown.',
    friendsNone: 'No friends yet. Add them on the Friends page in the app.',
    friendsOffline: 'Friends could not be loaded right now.',
    you: 'You',
    workoutsOfGoal: '{n}/{goal} workouts',
    cardioCount: '{n} cardio',
    tier1: 'Bronze',
    tier2: 'Silver',
    tier3: 'Gold',
    tier4: 'Diamond',
    tier0: 'not yet',
    ach_workouts: 'Workouts',
    ach_weeklyStreak: 'Weekly streak',
    ach_volume: 'Total volume',
    ach_records: 'Records',
    ach_bench: 'Bench press',
    ach_squat: 'Squat',
    ach_deadlift: 'Deadlift',
    ach_overheadPress: 'Overhead press',
    ach_runs: 'Cardio',
    ach_mealDays: 'Meal plan',
    ach_weighIns: 'Weigh-ins',
    ach_challenges: 'Daily challenges',
    ach_challengeStreak: 'Challenge streak',
    ach_teamChallenges: 'Team player',
    act_run: 'Running',
    act_walk: 'Walking',
    act_cycling: 'Cycling',
    act_rowing: 'Rowing',
    act_swimming: 'Swimming',
    act_elliptical: 'Elliptical',
    act_jumpRope: 'Jump rope',
    act_stairs: 'Stair climbing',
    act_hiit: 'HIIT',
    act_custom: 'Custom activity',
  },
};
